### PR TITLE
Classify uco-identity:Identity and subclasses

### PR DESCRIPTION
**Pull request by ajnelson-nist**

### CODE REVIEW

**Comment by ajnelson-nist** [comment]
@plbt5 , if you agree, please feel free to merge.

**Review by plbt5 — APPROVED** [review]
I'm not sure what is meant with eco-identity:Identity. If it's a collection of different concepts that provide administrative identities to individual objects, e.g., social security numbers, UUIDs, pasport numbers, make and model numbers etc., then the provided solution looks fine. If it is to be used to provide a principle of identity to its individuals, i.e., being a rigid sortal, then this is not the way to go. 
Since I do believe that you know the difference, I assume this to be meant according the first application.

**Comment by ajnelson-nist** [comment]
@plbt5 : `uco-identity:Identity` occupies the same space "Agent" would typically occupy in other models that have some grouping superclass of "person" and "organization," e.g. PROV, FOAF, Dublin Core Terms.

I'm not sure why "Agent" wasn't originally selected as the term, but that predates my CASE/UCO involvement.

Does that response change what the alignment of `uco-identity:Identity` should have been?

**Comment by plbt5** [comment]
@ajnelson-nist: That's weird name for what's supposed to represent Agents. Now this could work, since a `ufo:Category` is a rigid non-sortal that can collect individuals with different principle of identity. So I don't see a reason to change that alignment.

**Pull request merged**
